/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Hamburger(props) {
  const { nodes, materials } = useGLTF("/hamburger.glb");  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.topBun.geometry}
        material={materials.BunMaterial}
        // position={[0, 1.771, 0]}
        position={[0, 10.771, 0]}
      />      
       <mesh
        castShadow
        receiveShadow
        geometry={nodes.cheese.geometry}
        material={materials.CheeseMaterial}
        // position={[0, 3.04, 0]}
        position={[0, 9.04, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.meat.geometry}
        material={materials.SteakMaterial}
        // position={[0, 2.817, 0]}
        position={[0, 5.817, 0]}
      />
       <mesh castShadow receiveShadow geometry={nodes.bottomBun.geometry} material={materials.BunMaterial} />     
    </group>
  );
}

useGLTF.preload("/hamburger.glb");
